services:
  api-user-archetype:
    image: matfuentesv/api-user-archetype:1.0.0
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@FullStackIII_tp?TNS_ADMIN=/miapp/oracle_wallet/
      SPRING_DATASOURCE_USERNAME: Admin
      SPRING_DATASOURCE_PASSWORD: OracleCloud123
    restart: always
