version: '3.8'
services:
  api-user-archetype:
    image: matfuentesv/api-user-archetype:1.0.0
    ports:
      - "8082:8082" # Mapea el puerto del contenedor al host
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@FullStackIII_tp?TNS_ADMIN=/miapp/oracle_wallet/
      SPRING_DATASOURCE_USERNAME: Admin
      SPRING_DATASOURCE_PASSWORD: OracleCloud123
    restart: always
